/*
 * DaDaPush Public API
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dadapush.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.dadapush.client.model.MessagePushResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResultOfMessagePushResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-10T10:11:56.286885+08:00[Asia/Shanghai]")
public class ResultOfMessagePushResponse {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private MessagePushResponse data = null;

  public static final String SERIALIZED_NAME_ERRMSG = "errmsg";
  @SerializedName(SERIALIZED_NAME_ERRMSG)
  private String errmsg;

  public ResultOfMessagePushResponse code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "0", required = true, value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public ResultOfMessagePushResponse data(MessagePushResponse data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public MessagePushResponse getData() {
    return data;
  }

  public void setData(MessagePushResponse data) {
    this.data = data;
  }

  public ResultOfMessagePushResponse errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * Get errmsg
   * @return errmsg
  **/
  @ApiModelProperty(example = "ok", required = true, value = "")
  public String getErrmsg() {
    return errmsg;
  }

  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultOfMessagePushResponse resultOfMessagePushResponse = (ResultOfMessagePushResponse) o;
    return Objects.equals(this.code, resultOfMessagePushResponse.code) &&
        Objects.equals(this.data, resultOfMessagePushResponse.data) &&
        Objects.equals(this.errmsg, resultOfMessagePushResponse.errmsg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, data, errmsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultOfMessagePushResponse {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

